const questionBank = {

    1: [
        ["What is the capital city of Myanmar?", ["Yangon","Nay Pyi Taw","Mandalay","Bago"], 1],
        ["Which planet is known as the Red Planet?", ["Earth","Venus","Mars","Jupiter"], 2],
        ["How many continents are there?", ["5","6","7","8"], 2],
        ["Which is the largest ocean?", ["Atlantic","Indian","Arctic","Pacific"], 3],
        ["Which is the largest country by area?", ["China","Canada","Russia","USA"], 2],
        ["Which country is the Land of the Rising Sun?", ["China","Japan","Thailand","Korea"], 1],
        ["How many days are in a leap year?", ["364","365","366","367"], 2],
        ["What is the largest mammal?", ["Elephant","Blue Whale","Giraffe","Hippopotamus"], 1],
        ["Which country is famous for the Eiffel Tower?", ["Italy","France","Germany","Spain"], 1],
        ["What is the currency of the United Kingdom?", ["Euro","Dollar","Pound Sterling","Franc"], 2],
        ["Which is the largest planet?", ["Earth","Saturn","Jupiter","Neptune"], 2],
        ["Which animal is called the King of the Jungle?", ["Tiger","Lion","Elephant","Leopard"], 1],
        ["What is the capital of France?", ["London","Paris","Rome","Berlin"], 1],
        ["Which gas do humans need to breathe?", ["Nitrogen","Oxygen","Carbon dioxide","Hydrogen"], 1],
        ["How many days are in a normal year?", ["364","365","366","360"], 1],
        ["Which is the fastest land animal?", ["Lion","Cheetah","Horse","Tiger"], 1],
        ["Which country is home to the Great Wall?", ["Japan","India","China","Mongolia"], 2],
        ["How many colors are traditionally in a rainbow?", ["5","6","7","8"], 2],
        ["Which is the smallest planet?", ["Mars","Mercury","Venus","Neptune"], 1],
        ["What is the capital of Japan?", ["Kyoto","Osaka","Tokyo","Hiroshima"], 2]
    ],

    2: [
        ["Which is the longest river in Africa?", ["Congo","Nile","Niger","Zambezi"], 1],
        ["What is the currency of Japan?", ["Won","Yuan","Yen","Ringgit"], 2],
        ["Which gas makes up most of Earth's atmosphere?", ["Oxygen","CO2","Nitrogen","Hydrogen"], 2],
        ["Which is the smallest continent?", ["Europe","Australia","Antarctica","South America"], 1],
        ["Which country has the largest population?", ["USA","China","India","Indonesia"], 2],
        ["Which is the largest hot desert?", ["Gobi","Sahara","Kalahari","Arabian"], 1],
        ["Which organ pumps blood?", ["Brain","Lung","Heart","Kidney"], 2],
        ["Which metal is liquid at room temperature?", ["Iron","Gold","Mercury","Copper"], 2],
        ["Which planet is closest to the Sun?", ["Venus","Earth","Mercury","Mars"], 2],
        ["The pyramids of Giza are in which country?", ["Egypt","Greece","Mexico","Peru"], 0],
        ["What is the largest internal organ?", ["Heart","Liver","Lung","Kidney"], 1],
        ["Which instrument measures atmospheric pressure?", ["Thermometer","Barometer","Hygrometer","Anemometer"], 1],
        ["Which country is known as the Land of a Thousand Lakes?", ["Norway","Finland","Sweden","Iceland"], 1],
        ["What is the hardest natural substance?", ["Iron","Diamond","Quartz","Granite"], 1],
        ["Which vitamin is produced through sunlight exposure?", ["Vitamin A","Vitamin B","Vitamin C","Vitamin D"], 3],
        ["Mount Fuji is located in which country?", ["China","Japan","Korea","Nepal"], 1],
        ["What is the largest island in the world?", ["Madagascar","Greenland","Borneo","New Guinea"], 1],
        ["Which ocean lies between Africa, Asia and Australia?", ["Atlantic","Pacific","Indian","Arctic"], 2],
        ["Who formulated the laws of motion?", ["Einstein","Newton","Galileo","Tesla"], 1],
        ["Petra is located in which country?", ["Jordan","Lebanon","Syria","Israel"], 0]
    ],

    3: [
        ["Which strait connects the Atlantic Ocean and Mediterranean Sea?", ["Malacca","Gibraltar","Hormuz","Bering"], 1],
        ["Which mountain is the highest above sea level?", ["K2","Everest","Lhotse","Kangchenjunga"], 1],
        ["Which country is the world's largest coffee producer?", ["Brazil","Vietnam","Colombia","Indonesia"], 0],
        ["Where is the headquarters of the United Nations?", ["Geneva","New York","Paris","Vienna"], 1],
        ["Which canal connects the Atlantic and Pacific Oceans?", ["Suez","Panama","Kiel","Corinth"], 1],
        ["Which strait connects the Persian Gulf with Gulf of Oman?", ["Hormuz","Bosporus","Malacca","Bering"], 0],
        ["Which organization regulates international civil aviation?", ["IMO","ICAO","WHO","ILO"], 1],
        ["Machu Picchu is located in which country?", ["Mexico","Peru","Chile","Bolivia"], 1],
        ["Which sea lies between Europe and Africa?", ["Caribbean","Mediterranean","Arabian","South China"], 1],
        ["Which country has the largest area in Africa?", ["Egypt","Algeria","Sudan","Libya"], 1],
        ["Which river flows through Egypt?", ["Amazon","Nile","Danube","Mekong"], 1],
        ["Which country has Canberra as its capital?", ["Australia","Canada","New Zealand","South Africa"], 0],
        ["Which city is known as the Big Apple?", ["Los Angeles","New York","Chicago","Boston"], 1],
        ["Which country is home to the Amazon rainforest's largest share?", ["Brazil","Peru","Colombia","Bolivia"], 0],
        ["Which is the deepest ocean?", ["Atlantic","Indian","Pacific","Arctic"], 2],
        ["Which continent contains the Sahara Desert?", ["Asia","Africa","Europe","Australia"], 1],
        ["Which country is famous for the ancient city of Angkor?", ["Thailand","Cambodia","Vietnam","Laos"], 1],
        ["Which lake is the largest freshwater lake by surface area?", ["Victoria","Superior","Baikal","Tanganyika"], 1],
        ["Which country controls the Panama Canal?", ["Panama","USA","Colombia","Mexico"], 0],
        ["Which city is the capital of Canada?", ["Toronto","Vancouver","Ottawa","Montreal"], 2]
    ],

    4: [
        ["Which treaty established the European Union?", ["Rome","Maastricht","Lisbon","Versailles"], 1],
        ["Which organization is responsible for global monetary cooperation?", ["IMF","WTO","WHO","UNESCO"], 0],
        ["Which country controls the Bosporus Strait?", ["Greece","Türkiye","Egypt","Italy"], 1],
        ["Which agreement created the WTO?", ["Paris Agreement","Marrakesh Agreement","Kyoto Protocol","Doha Declaration"], 1],
        ["Which is the principal judicial organ of the UN?", ["ICC","ICJ","PCA","ECHR"], 1],
        ["Which country is NOT a permanent UN Security Council member?", ["China","France","Germany","Russia"], 2],
        ["Which canal connects the Mediterranean and Red Seas?", ["Panama","Suez","Kiel","Corinth"], 1],
        ["Which organization is responsible for global public health?", ["WHO","IMF","WTO","ILO"], 0],
        ["Which country is an archipelago in Southeast Asia?", ["Indonesia","Nepal","Mongolia","Bhutan"], 0],
        ["Which agreement focuses on climate change and was adopted in 2015?", ["Kyoto Protocol","Paris Agreement","Montreal Protocol","Rome Treaty"], 1],
        ["Which organization promotes international labor standards?", ["ILO","IMF","WTO","ICAO"], 0],
        ["Which treaty created NATO?", ["Treaty of Rome","North Atlantic Treaty","Maastricht Treaty","Lisbon Treaty"], 1],
        ["Which organization is responsible for international trade rules?", ["WTO","WHO","UNESCO","ILO"], 0],
        ["Which country is a member of the G7?", ["India","Germany","Brazil","Australia"], 1],
        ["Which city hosts the headquarters of the IMF?", ["New York","Washington, D.C.","Geneva","Paris"], 1],
        ["Which sea route connects the Red Sea to the Gulf of Aden?", ["Bab el-Mandeb","Bosporus","Bering","Dardanelles"], 0],
        ["Which international organization has its headquarters in Geneva and deals with health?", ["WHO","WTO","IMF","UNDP"], 0],
        ["Which country is a permanent member of the UN Security Council?", ["Germany","Japan","India","France"], 3],
        ["Which treaty ended World War I with Germany?", ["Treaty of Paris","Treaty of Versailles","Treaty of Rome","Treaty of Tordesillas"], 1],
        ["Which organization provides international development loans and assistance?", ["World Bank","NATO","WHO","ICAO"], 0]
    ],

    5: [
        ["Which concept refers to influence through attraction?", ["Hard power","Soft power","Balance of power","Collective security"], 1],
        ["Which five states are permanent members of the UN Security Council?", ["China, France, Russia, UK, USA","China, India, Russia, UK, USA","France, Germany, Russia, UK, USA","China, France, Germany, Russia, USA"], 0],
        ["Which principle emphasizes peaceful settlement of international disputes?", ["Negotiation and peaceful means","Military intervention","Use of force","Economic isolation"], 0],
        ["Which institution is associated with global trade rules?", ["WTO","IMF","WHO","UNESCO"], 0],
        ["What term describes diversification of strategic partnerships?", ["Strategic diversification","Isolationism","Autarky","Neutrality"], 0],
        ["Which principle prohibits interference in another state's internal affairs?", ["Non-intervention","Collective defence","Deterrence","Protectionism"], 0],
        ["Which UN organ includes all member states?", ["Security Council","General Assembly","ICJ","Secretariat"], 1],
        ["Which IR theory emphasizes ideas and identities?", ["Realism","Liberalism","Constructivism","Mercantilism"], 2],
        ["What describes distribution of power among states?", ["Balance of power","Soft power","Globalization","Integration"], 0],
        ["Which organization is the main forum for international peace and security?", ["United Nations","WTO","IMF","OECD"], 0],
        ["What is deterrence primarily intended to do?", ["Discourage an adversary from taking an action","Increase trade","Promote tourism","Reduce population"], 0],
        ["Which principle is associated with state sovereignty?", ["Non-interference","Free trade","Collective punishment","Open borders"], 0],
        ["What does BRI stand for?", ["Belt and Road Initiative","Blue Road Initiative","Business Relations Initiative","Bilateral Regional Integration"], 0],
        ["What does ASEAN stand for?", ["Association of Southeast Asian Nations","Asian Economic Nations","Association of South Asian Nations","Asia-Pacific Economic Network"], 0],
        ["What does NATO stand for?", ["North Atlantic Treaty Organization","Northern Asian Trade Organization","National Atlantic Trade Organization","North American Treaty Office"], 0],
        ["Which concept means the ability to shape others' preferences through attraction?", ["Soft power","Hard power","Military power","Economic coercion"], 0],
        ["Which UN body has primary responsibility for international peace and security?", ["Security Council","General Assembly","ECOSOC","Secretariat"], 0],
        ["Which principle is central to collective security?", ["An attack against one is a concern for all members","Complete isolation","Unilateral action","Trade protection"], 0],
        ["Which concept refers to cooperation among states through institutions?", ["Multilateralism","Isolationism","Unilateralism","Autarky"], 0],
        ["What is public diplomacy mainly concerned with?", ["Engaging and communicating with foreign publics","Military operations","Domestic taxation","Border construction"], 0]
    ]

};